version: '3'

services:
  crawler:
    build: '.'
    container_name: crawler
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27010:27017